// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

import * as Block      from "../../../../node_modules/bs-platform/lib/es6/block.js";
import * as Pervasives from "../../../../node_modules/bs-platform/lib/es6/pervasives.js";

console.log(/* No */1);

var myAccount = /* Face */Block.__(1, [
    "arvin",
    24
  ]);

var myName;

myName = typeof myAccount === "number" ? "fck" : (
    myAccount.tag ? "hi arvin,you are " + (Pervasives.string_of_int(24) + " years old") : "hello arvin!"
  );

console.log(myName);

var fck = /* No */1;

var myInstagram = /* Instagram */Block.__(0, ["hehe"]);

export {
  fck         ,
  myAccount   ,
  myInstagram ,
  myName      ,
  
}
/*  Not a pure module */
