// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

import * as Test$WonderReasonTest from "./test.js";

console.log(Test$WonderReasonTest.b);

var Test111 = 0;

var a = Test$WonderReasonTest.b;

export {
  Test111 ,
  a       ,
  
}
/*  Not a pure module */
