// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';


var message = "hehe";

console.log(message);

var a = "asfd";

var b = "wfgwefef";

console.log("asfdwfgwefef");

var Test111 = 0;

var isPass = /* false */0;

export {
  Test111 ,
  isPass  ,
  message ,
  a       ,
  b       ,
  
}
/*  Not a pure module */
