// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';


var you = /* record */[
  /* age */13,
  /* name */"arvin"
];

var he = /* record */[
  /* name */"hehe",
  /* age */1
];

he[/* age */1] = 12;

var me = /* record */[
  /* age */12,
  /* name */"arvin"
];

export {
  me  ,
  you ,
  he  ,
  
}
/*  Not a pure module */
