// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';


var ageAndName = /* tuple */[
  24,
  "arvin"
];

console.log(ageAndName);

export {
  ageAndName ,
  
}
/*  Not a pure module */
